import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import Layout from '../../components/Layout';
import Loading from '../../components/Loading';

export default function ArticlePage() {
  const router = useRouter();
  const { id } = router.query;
  const [article, setArticle] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!id) return;
    const base = process.env.NEXT_PUBLIC_API_BASE || 'http://localhost:4000';
    fetch(`${base}/articles/${id}`)
      .then(r => {
        if (!r.ok) throw new Error('Article not found');
        return r.json();
      })
      .then(setArticle)
      .catch(err => {
        console.error(err);
        setError(err.message);
      });
  }, [id]);

  const formatDate = (dateString) => {
    const options = { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' };
    return new Date(dateString).toLocaleDateString('en-US', options);
  };

  return (
    <Layout>
      <div className="max-w-4xl mx-auto">
        {/* Back Button */}
        <Link href="/">
          <div className="inline-flex items-center text-gold hover:text-stone transition-colors cursor-pointer mb-8 group">
            <svg
              className="w-5 h-5 mr-2 transform group-hover:-translate-x-1 transition-transform"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M15 19l-7-7 7-7"
              />
            </svg>
            Back to Articles
          </div>
        </Link>

        {!article && !error && <Loading />}

        {error && (
          <div className="bg-red-100 border border-red-400 text-red-700 px-6 py-4 rounded-lg">
            <h2 className="font-bold text-lg mb-2">Error</h2>
            <p>{error}</p>
          </div>
        )}

        {article && (
          <article className="bg-white rounded-xl shadow-lg overflow-hidden">
            {/* Article Header */}
            <div className="bg-gradient-to-r from-charcoal to-stone p-8">
              <span className="inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-gold text-charcoal mb-4">
                AI Generated Article
              </span>
              <h1 className="text-4xl md:text-5xl font-bold text-white mb-4 leading-tight">
                {article.title}
              </h1>
              <div className="flex items-center text-cream text-sm">
                <svg
                  className="w-5 h-5 mr-2"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
                  />
                </svg>
                Published on {formatDate(article.createdAt)}
              </div>
            </div>

            {/* Article Content */}
            <div className="p-8 md:p-12">
              <div className="prose prose-lg max-w-none">
                <p className="text-charcoal text-lg leading-relaxed whitespace-pre-wrap">
                  {article.content}
                </p>
              </div>
            </div>

            {/* Article Footer */}
            <div className="bg-cream p-6 border-t border-stone/20">
              <div className="flex items-center justify-between">
                <p className="text-sm text-stone">
                  Generated by AI • AutoBlog Platform
                </p>
                <Link href="/">
                  <span className="text-gold hover:text-charcoal font-medium cursor-pointer transition-colors">
                    Read More Articles →
                  </span>
                </Link>
              </div>
            </div>
          </article>
        )}
      </div>
    </Layout>
  );
}
